### ISSUE TITLE
[Question] Can I use this without Digma ? 

### ISSUE THREAD

**Issue by slamer59** [digma-ai/opentelemetry-instrumentation-digma#34]
Hello,
I have a project full of opentracing/ opentelemetry span. I was looking on how to implement **decorators** and found your excelent article @doppleware 

Since I have a lot of rework for moving opentracing -> opentelemetry, I wonder if I can do a step by step with this implementation. 
And why not using Digma when I have some times. 

regards

**Comment by doppleware** [comment]
Hi,
Sure! The decorator does not require Digma.
Thanks!
Roni
